[package]
name = "daoyi-module-system-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
salvo.workspace = true
anyhow.workspace = true
daoyi-common.workspace = true
daoyi-starter-app.workspace = true